# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CatchMe' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CatchMe

    pod 'NMapsMap', '~> 3.2.0'
    pod 'Alamofire', '~> 4.8.2'
    pod 'SwiftyJSON', '~> 4.0'

end
